version: '3.8'

services:
  app:
    container_name: flow_app
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/var/www/html
      - .docker/php/conf.d/local.ini:/usr/local/etc/php/conf.d/local.ini
      - .docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - .docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    extra_hosts:
      - "host.docker.internal:host-gateway"
    mem_limit: 1024m
    mem_reservation: 512M
    depends_on:
      - mysql
    networks:
      - app-network
    ports:
      - 5000:5000

  mysql:
    container_name: flow_mysql
    platform: linux/x86_64
    build:
      context: .
      dockerfile: .docker/mysql/Dockerfile
    volumes:
      - .docker/mysql/init:/docker-entrypoint-initdb.d
      - .docker/mysql/my.conf:/etc/mysql/mysqld.cnf
    mem_limit: 1024m
    mem_reservation: 512M
    ports:
      - "3307:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_DATABASE: flow
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - app-network

  phpmyadmin:
    container_name: flow_phpmyadmin
    build:
      context: .
      dockerfile: .docker/phpmyadmin/Dockerfile
    links:
      - mysql:mysql
    mem_limit: 1024m
    mem_reservation: 512M
    ports:
      - 8888:80
    environment:
      USER: root
      MYSQL_HOST: mysql
      MYSQL_USER: root
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - app-network
  
networks:
  app-network:
    driver: "bridge"
